//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myriadbits.MXFInspect.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Myriadbits.MXFInspect.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ChildIcon {
            get {
                object obj = ResourceManager.GetObject("ChildIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CollapseAll {
            get {
                object obj = ResourceManager.GetObject("CollapseAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- *****DO NOT EDIT THIS XML FILE******* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- DRAFT REGISTER --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- SMPTE METADATA REGISTER --&gt;
        ///&lt;!-- ####################### --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- See https://registry.smpte-ra.org for SMPTE M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Elements {
            get {
                return ResourceManager.GetString("Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FilteredObject_13400_14x {
            get {
                object obj = ResourceManager.GetObject("FilteredObject_13400_14x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindNext_13243 {
            get {
                object obj = ResourceManager.GetObject("FindNext_13243", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FindPrevious_13244 {
            get {
                object obj = ResourceManager.GetObject("FindPrevious_13244", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- *****DO NOT EDIT THIS XML FILE******* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- DRAFT REGISTER --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- SMPTE METADATA REGISTER --&gt;
        ///&lt;!-- ####################### --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- See https://registry.smpte-ra.org for SMPTE M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HideMember_6755 {
            get {
                object obj = ResourceManager.GetObject("HideMember_6755", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- *****DO NOT EDIT THIS XML FILE******* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- DRAFT REGISTER --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- SMPTE METADATA REGISTER --&gt;
        ///&lt;!-- ####################### --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- See https://registry.smpte-ra.org for SMPTE M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                     GNU GENERAL PUBLIC LICENSE
        ///                       Version 2, June 1991
        ///
        /// Copyright (C) 1989, 1991 Free Software Foundation, Inc.,
        /// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The licenses for most software are designed to take away your
        ///freedom to share and change it.  By contrast, the GNU General Publi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LICENSE {
            get {
                return ResourceManager.GetString("LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open_6529 {
            get {
                object obj = ResourceManager.GetObject("Open_6529", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RSReport_16xLG {
            get {
                object obj = ResourceManager.GetObject("RSReport_16xLG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings {
            get {
                object obj = ResourceManager.GetObject("settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap showInfo {
            get {
                object obj = ResourceManager.GetObject("showInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- *****DO NOT EDIT THIS XML FILE******* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!-- ************************************* --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- DRAFT REGISTER --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- SMPTE METADATA REGISTER --&gt;
        ///&lt;!-- ####################### --&gt;
        ///&lt;!--  --&gt;
        ///&lt;!-- See https://registry.smpte-ra.org for SMPTE M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
    }
}
