//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myriadbits.MXF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Myriadbits.MXF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type;DID;SDID;Status;Used Where;Application;Last Modified Time
        ///;00h;;Deprecated;S291;Undefined data deleted, (Deprecated; revision of ST291-2010);2010-07-11 14:26:49
        ///2;08h;08h;In Force;S353;MPEG recoding data, VANC space;2010-07-11 14:26:49
        ///2;08h;0Ch;In Force;S353;MPEG recoding data, HANC space;2010-07-15 17:25:46
        ///2;40h;01h;In Force;S305;SDTI transport in active frame space;2010-07-11 14:26:49
        ///2;40h;02h;In Force;S348;HD-SDTI transport in active frame space;2010-07-11 14:26:49
        ///2;40h;04h;In Force;S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ANC_Identifiers {
            get {
                return ResourceManager.GetString("ANC_Identifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _;SMPTE Metadata Elements Dictionary;;;;;;;;;;;;;
        ///_;Published version 13 as of 2012-02-14;;;;;;;;;;;;;
        ///_ver;Published;13;;;;;;;;;;;;
        ///_;;499;Nodes in this Register;;;;;;;;;;;
        ///_;;1476;Leaves in this Register;;;;;;;;;;;
        ///_;Register;Dictionary Version at introduction;Node or
        ///Leaf;Level;Universal Label;Metadata Element Name;Metadata Element Definition;Type;Value Length;Value Range;;;Defining Document;Notes
        ///;Elements;1;Node;0;06.0E.2B.34.01.01.01.01.00.00.00.00.00.00.00.00;ELEMENTS;Register of individual Met [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MD_Identifiers {
            get {
                return ResourceManager.GetString("MD_Identifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type;Registry Designator;Item Designator;Ver;Reference Name;Description;Standard(s);;Deprecated
        ///Nrm;Normative;Normative;Nrm;Normative;Normative;Normative;Notes;Nrm
        ///Node or Leaf;Note: Byte 8 is the version number of the registry at the point of Label registration;;;;;(where applicable);;
        ///Node;06.0E.2B.34.04.01.01.01;00.00.00.00.00.00.00.00;01;SMPTE LABELS;Register of SMPTE Labels;SMPTE ST 400;;
        ///Node;06.0E.2B.34.04.01.01.01;01.00.00.00.00.00.00.00;01;IDENTIFICATION AND LOCATION;SMPTE Label Identifiers for [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UL_Identifiers {
            get {
                return ResourceManager.GetString("UL_Identifiers", resourceCulture);
            }
        }
    }
}
