//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Myriadbits.MXF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Myriadbits.MXF.Properties.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Partition contains Index Table Segments.
        /// </summary>
        internal static string ID_0051 {
            get {
                return ResourceManager.GetString("ID_0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one Body Partition contains Index Table Segments.
        /// </summary>
        internal static string ID_0052 {
            get {
                return ResourceManager.GetString("ID_0052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Partition contains Index Table Segments.
        /// </summary>
        internal static string ID_0053 {
            get {
                return ResourceManager.GetString("ID_0053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Body Partition(s) present.
        /// </summary>
        internal static string ID_0054 {
            get {
                return ResourceManager.GetString("ID_0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid partition structure. The first partition must be a Header Partition.
        /// </summary>
        internal static string ID_0055 {
            get {
                return ResourceManager.GetString("ID_0055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid partition structure. Only the first partition shall be a Header Partition.
        /// </summary>
        internal static string ID_0056 {
            get {
                return ResourceManager.GetString("ID_0056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid partition structure. Only the last partition can be a Footer Partition.
        /// </summary>
        internal static string ID_0057 {
            get {
                return ResourceManager.GetString("ID_0057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Partition does not contain header metadata .
        /// </summary>
        internal static string ID_0058 {
            get {
                return ResourceManager.GetString("ID_0058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIP entry {0} not pointing to a partition location.
        /// </summary>
        internal static string ID_0062 {
            get {
                return ResourceManager.GetString("ID_0062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid partition structure. The last partition is not a Footer Partition.
        /// </summary>
        internal static string ID_0063 {
            get {
                return ResourceManager.GetString("ID_0063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid partition structure. The last partition is not a Footer Partition.
        /// </summary>
        internal static string ID_0064 {
            get {
                return ResourceManager.GetString("ID_0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Operational Pattern property is not consistent across all partitions.
        /// </summary>
        internal static string ID_0065 {
            get {
                return ResourceManager.GetString("ID_0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KLV Validator.
        /// </summary>
        internal static string ID_0066 {
            get {
                return ResourceManager.GetString("ID_0066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIP/ KAG.
        /// </summary>
        internal static string ID_0067 {
            get {
                return ResourceManager.GetString("ID_0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KLV Validator.
        /// </summary>
        internal static string ID_0068 {
            get {
                return ResourceManager.GetString("ID_0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KLV Validator?.
        /// </summary>
        internal static string ID_0069 {
            get {
                return ResourceManager.GetString("ID_0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KLV Validator?.
        /// </summary>
        internal static string ID_0070 {
            get {
                return ResourceManager.GetString("ID_0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KLV/ KAG.
        /// </summary>
        internal static string ID_0071 {
            get {
                return ResourceManager.GetString("ID_0071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KLV.
        /// </summary>
        internal static string ID_0072 {
            get {
                return ResourceManager.GetString("ID_0072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KLV/Partition Validator.
        /// </summary>
        internal static string ID_0073 {
            get {
                return ResourceManager.GetString("ID_0073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Index Pack present.
        /// </summary>
        internal static string ID_0074 {
            get {
                return ResourceManager.GetString("ID_0074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Random Index Pack detected.
        /// </summary>
        internal static string ID_0075 {
            get {
                return ResourceManager.GetString("ID_0075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAG.
        /// </summary>
        internal static string ID_0084 {
            get {
                return ResourceManager.GetString("ID_0084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAG.
        /// </summary>
        internal static string ID_0085 {
            get {
                return ResourceManager.GetString("ID_0085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAG.
        /// </summary>
        internal static string ID_0090 {
            get {
                return ResourceManager.GetString("ID_0090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KLV / Metadata.
        /// </summary>
        internal static string ID_0091 {
            get {
                return ResourceManager.GetString("ID_0091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Partition status is &quot;open&quot; (= required values may be absent).
        /// </summary>
        internal static string ID_0092 {
            get {
                return ResourceManager.GetString("ID_0092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAG.
        /// </summary>
        internal static string ID_0093 {
            get {
                return ResourceManager.GetString("ID_0093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAG.
        /// </summary>
        internal static string ID_0094 {
            get {
                return ResourceManager.GetString("ID_0094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition #{0} has incorrect value for ThisPartition.
        /// </summary>
        internal static string ID_0095 {
            get {
                return ResourceManager.GetString("ID_0095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition #{0} has incorrect value for PreviousPartition.
        /// </summary>
        internal static string ID_0096 {
            get {
                return ResourceManager.GetString("ID_0096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition #{0} has incorrect value for FooterPartition.
        /// </summary>
        internal static string ID_0097 {
            get {
                return ResourceManager.GetString("ID_0097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition #{0} has incorrect value for HeaderByteCount.
        /// </summary>
        internal static string ID_0098 {
            get {
                return ResourceManager.GetString("ID_0098", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAG.
        /// </summary>
        internal static string ID_0106 {
            get {
                return ResourceManager.GetString("ID_0106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition #{0} Major Version property has an invalid value (read: {1}, expected: 1).
        /// </summary>
        internal static string ID_0107 {
            get {
                return ResourceManager.GetString("ID_0107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partition #{0} Minor Version property has an invalid value (read: {1}, expected: 2 or 3).
        /// </summary>
        internal static string ID_0108 {
            get {
                return ResourceManager.GetString("ID_0108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preface.
        /// </summary>
        internal static string ID_0110 {
            get {
                return ResourceManager.GetString("ID_0110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preface.
        /// </summary>
        internal static string ID_0111 {
            get {
                return ResourceManager.GetString("ID_0111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $&quot;Partition #{0} has an invalid PartitionStatus (0x{1:X2})&quot;.
        /// </summary>
        internal static string ID_0114 {
            get {
                return ResourceManager.GetString("ID_0114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Major/Minor Version property is not consistent across all partitions.
        /// </summary>
        internal static string ID_0707 {
            get {
                return ResourceManager.GetString("ID_0707", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Partition present.
        /// </summary>
        internal static string ID_0708 {
            get {
                return ResourceManager.GetString("ID_0708", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Footer Partition, if present, must be closed.
        /// </summary>
        internal static string ID_0709 {
            get {
                return ResourceManager.GetString("ID_0709", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FooterPartition value of Partition #{0} is non-zero but the file has no Footer Partition.
        /// </summary>
        internal static string ID_0710 {
            get {
                return ResourceManager.GetString("ID_0710", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No partitions detected.
        /// </summary>
        internal static string ID_0711 {
            get {
                return ResourceManager.GetString("ID_0711", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RIP contains extraneous (non RIP entries) elements.
        /// </summary>
        internal static string ID_0712 {
            get {
                return ResourceManager.GetString("ID_0712", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of RIP entries is not equal to the number of partitions ({0} vs {1}).
        /// </summary>
        internal static string ID_0713 {
            get {
                return ResourceManager.GetString("ID_0713", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no RIP entry for Partition #{0}.
        /// </summary>
        internal static string ID_0714 {
            get {
                return ResourceManager.GetString("ID_0714", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIP entries are not stored in ascending Byte Offset order.
        /// </summary>
        internal static string ID_0715 {
            get {
                return ResourceManager.GetString("ID_0715", resourceCulture);
            }
        }
    }
}
