name: Sample Matrix Parallel

on:
  push:
    branches:
      - testaction

jobs:
  #setup:

  create_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          win-version: [x64, x86]
    steps:
        - name: Create a file
          run: echo ${{ matrix.win-version }} > my_file.txt
        
        - name: Upload multiple artifacts via multiple jobs
          uses: actions/upload-artifact@v2
          with:
              name: my-artifact-${{ matrix.win-version }}
              path: ${{ github.workspace }}
  
  do_release:
      needs: create_matrix
      runs-on: ubuntu-latest
      steps:
        - name: release
          uses: actions/create-release@v1
          id: create_release
          with:
            draft: false
            prerelease: false
            #release_name: ${{ steps.version.outputs.version }}
            #tag_name: ${{ github.ref }}
            #body_path: CHANGELOG.md
          env:
            GITHUB_TOKEN: ${{ github.token }}
            
  download: 
      needs: do_release
      runs-on: ubuntu-latest
      strategy:
        matrix:
          win-version: [x64, x86]
      steps:
        - name: Download build artifact        
        - uses: actions/download-artifact@v2
          with:
              name: my-artifact-${{ matrix.win-version }}