name: Sample Matrix Parallel

#on:
#  push:
#    branches:
#      - testaction

on:
  push:
    tags:
      - '*'

jobs:
  #setup:

  create_matrix:
    runs-on: ubuntu-latest
    outputs:
      tag_nome: ${GITHUB_REF#refs/tags/}
    strategy:
      matrix:
          win-version: [x64, x86]
    steps:
        - name: Get the version
          id: get_version
          run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

        - name: Create a file
          run: echo ${{ matrix.win-version }} > my_file${{ matrix.win-version }}.txt
        
        - name: Upload multiple artifacts via multiple jobs
          uses: actions/upload-artifact@v2
          with:
              name: my-artifact-${{ matrix.win-version }}
              path: ${{ github.workspace }}

        - name: Show Files
          run: ls -lr
  
  do_release:
      needs: create_matrix
      runs-on: ubuntu-latest
      outputs:
        url: ${{ steps.create_release.outputs.upload_url }}
      steps:
        - name: Create a release
          id: create_release
          uses: actions/create-release@v1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          with:
            tag_name: ${GITHUB_REF#refs/tags/}
            release_name: Release ${GITHUB_REF#refs/tags/}
            #release_name: ${{ steps.version.outputs.version }}
            #tag_name: ${{ github.ref }}
            #body_path: CHANGELOG.md
            body: |
              Changes in this Release
              - First Change
              - Second Change
            draft: false
            prerelease: true

#        - name: echo
#          run: echo ${{ do_release.create_release.outputs.upload_url }}

  download: 
      needs: do_release
      runs-on: ubuntu-latest
      strategy:
        matrix:
          win-version: [x64, x86]
      steps:
        - name: Download build artifact        
          uses: actions/download-artifact@v2
          with:
              name: my-artifact-${{ matrix.win-version }}

        - name: Show path       
          run: echo ${{ github.workspace }}

        - name: Show path       
          run: ls -lr
        
        - name: Upload build artifact to release
          id: upload-release-asset 
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ needs.do_release.outputs.url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
            asset_path: ./
            asset_name: my_file${{ matrix.win-version }}.txt
            asset_content_type: text/plain