name: Create release from tag

#on:
#  push:
#    branches:
#      - testaction

on:
  push:
    tags:
      - 'v*'

jobs:
  get_version:
    name: Get version tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
        - name: Get the tag string (cleaned)
          id: get_version
          run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
        
        - name: Echo the tag (for debugging)
          run: echo ${{ steps.get_version.outputs.VERSION }}

  create_builds:
    name: Build, Test & Publish
    needs: get_version
    runs-on: ubuntu-latest
    env: 
        VERSION: "${{ needs.get_version.outputs.version }}"
        ARTIFACT_NAME: "MXFInspect-${{ needs.get_version.outputs.version }}-win-${{ matrix.win-version }}"
    strategy:
      matrix:
          win-version: [x64, x86]
    steps:
        - name: Echo the environment variables (for debugging)
          run: |
            echo "VERSION = $VERSION"
            echo "ARTIFACT_NAME = $ARTIFACT_NAME"

        - name: Create a file and zip it
          run: |
            echo ${{ matrix.win-version }} > $ARTIFACT_NAME.txt
            7z a $ARTIFACT_NAME.zip $ARTIFACT_NAME.txt -bb

        - name: Upload multiple artifact
          uses: actions/upload-artifact@v2
          with:
              name: ${{ env.ARTIFACT_NAME }}
              path: ./*.zip

  
  do_release:
      name: Create release
      needs: [get_version, create_builds]
      runs-on: ubuntu-latest
      env: 
        VERSION: "${{ needs.get_version.outputs.version }}"
      outputs:
        url: ${{ steps.create_release.outputs.upload_url }}
      steps:
        - name: Show the version tag (for debugging)
          run: echo "VERSION = $VERSION"
                
        - name: Create a release
          id: create_release
          uses: actions/create-release@v1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          with:
            tag_name: ${{ env.VERSION }}
            release_name: ${{ env.VERSION }} Release of MXFInspect
            #body_path: CHANGELOG.md
            body: |
              Changes in this Release
              - First Change
              - Second Change
            draft: false
            prerelease: true


  upload_release: 
      name: Upload release artifacts
      needs: [get_version, do_release]
      runs-on: ubuntu-latest
      env: 
        VERSION: "${{ needs.get_version.outputs.version }}"
        ARTIFACT_NAME: "MXFInspect-${{ needs.get_version.outputs.version }}-win-${{ matrix.win-version }}"
        UPLOAD_URL: "${{ needs.do_release.outputs.url }}"
      strategy:
        matrix:
          win-version: [x64, x86]
      steps:
        - name: Echo environment variables (for debugging)       
          run: |
              echo "VERSION = $VERSION"
              echo "ARTIFACT_NAME = $ARTIFACT_NAME"
              echo "UPLOAD_URL = $UPLOAD_URL"

        - name: Download build artifact        
          uses: actions/download-artifact@v2
          with:
              name: ${{ env.ARTIFACT_NAME }}
       
        - name: Upload build artifacts to release
          id: upload-release-asset 
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ env.UPLOAD_URL }} 
            asset_path: ./${{ env.ARTIFACT_NAME }}.zip
            asset_name: ${{ env.ARTIFACT_NAME }}.zip
            asset_content_type: application/zip